include: "rules/common.smk"


module dna_seq_varlociraptor:
    snakefile:
        github(
            "snakemake-workflows/dna-seq-varlociraptor",
            path="workflow/Snakefile",
            tag="v3.14.0",
        )
    config:
        config


use rule * from dna_seq_varlociraptor


if "normal"  in dna_seq_varlociraptor.samples["alias"]:
    tissue_counts = dna_seq_varlociraptor.samples.groupby("alias").size()
    if tissue_counts["normal"] != tissue_counts["tumor"]:
        raise WorkflowError(
            "Invalid definition of tumor and normal samples in sample sheet. Only tumor/normal or tumor only groups are allowed at once."
        )

if not "ffpe" in dna_seq_varlociraptor.samples.columns:
    dna_seq_varlociraptor.samples["ffpe"] = 0
elif (
    dna_seq_varlociraptor.samples.loc[
        dna_seq_varlociraptor.samples["alias"] == "normal", "ffpe"
    ]
    == 1
).any():
    raise WorkflowError(
        "Invalid value for ffpe column in sample sheet. ffpe treated normal samples are not supported."
    )

for sample, events in zip(
    ["normal", "tumor"],
    ["germline,loh,loh_or_amplification", "somatic_tumor_low,somatic_tumor_high"],
):
    dna_seq_varlociraptor.samples.loc[
        dna_seq_varlociraptor.samples["alias"] == sample, "mutational_burden_events"
    ] = events
