include: "rules/common.smk"


module dna_seq_varlociraptor:
    snakefile:
        github(
            "snakemake-workflows/dna-seq-varlociraptor",
            path="workflow/Snakefile",
            branch="datavzrd",  # TODO use release once done
        )
    config:
        config


use rule * from dna_seq_varlociraptor
